# pd.DataFrame.iterrows()
데이터 프레임을 반복할 때 사용하는 attribute

``` python
for row in df.iterrows():
  row[index][column_index]
```

In [4]:
import pandas as pd

df = pd.DataFrame({'column1':[1, 3, 5, 7], 'column2':[2, 4, 6, 8]})
df

   column1  column2
0        1        2
1        3        4
2        5        6
3        7        8

In [2]:
for row in df.iterrows():
  print('row[0] : ', row[0])
  print('row[1] : ', row[1])

row[0] :  0
row[1] :  column1    1
column2    2
Name: 0, dtype: int64
row[0] :  1
row[1] :  column1    3
column2    4
Name: 1, dtype: int64
row[0] :  2
row[1] :  column1    5
column2    6
Name: 2, dtype: int64
row[0] :  3
row[1] :  column1    7
column2    8
Name: 3, dtype: int64

위의 반복문을 확인하면 `row[0]`는 Index를 `row[1]`는 행의 모든 컬럼에 따른 값을 출력한다.  
그렇다면, 컬럼에 해당하는 값을 얻기 위해서는 어떻게 해야할까?

In [3]:
for row in df.iterrows():
  print('first column : ', row[1][0])
  print('second column : ', row[1][1])

first column :  1
second column :  2
first column :  3
second column :  4
first column :  5
second column :  6
first column :  7
second column :  8

위와 같이 column의 index를 입력해주면 해당 값을 얻을 수 있다.